format_version: '1.2'
id: 67315492-5fb3-4d3c-8f54-787b94d914df
name: Corn
hierarchy:
- type: Folder
  id: 30e32a52-15e6-4ffa-9518-132228148851
  name: Manuscript
  children:
  - type: Document
    id: cdf11353-7574-47d7-92cd-4c6dd54328ed
    name: Short Story Format
    path: manuscript/short-story-format.md
  - type: Document
    id: 153fd091-fba2-4de8-a527-1300ab18ff79
    name: Opening
    path: manuscript/opening.md
  - type: Document
    id: 9986d1d1-1b60-4fe1-b0ed-c2359582fb1f
    name: Shelly & Marcus setup
    path: manuscript/shelly-marcus-setup.md
  - type: Document
    id: de777628-41a1-4fa6-bfc2-b56212bbc60d
    name: Shelly & Corn meet
    path: manuscript/shelly-corn-meet.md
  - type: Document
    id: 9cf2426c-1d00-4de1-9083-e922633dddd1
    name: S&C Falling
    path: manuscript/s-c-falling.md
  - type: Document
    id: 271e259c-3805-4d2b-b5a9-9596bf065a55
    name: S&C Getting intimate
    path: manuscript/s-c-getting-intimate.md
  - type: Document
    id: 1b4191df-8178-469f-b2b4-170d14d47038
    name: Daddy's letter arrives
    path: manuscript/daddy-s-letter-arrives.md
  - type: Document
    id: d95b90d7-98ef-44fa-9bb6-c5978a3254e9
    name: Shelly's house, Corn vs Kelly
    path: manuscript/shelly-s-house-corn-vs-kelly.md
  - type: Document
    id: 5d499dda-9d9a-4ae8-a8e7-7141e06a6fb0
    name: Motel confrontation
    path: manuscript/motel-confrontation.md
  - type: Document
    id: 9a56cb72-188a-442d-92ab-1cd28542511f
    name: Closing
    path: manuscript/closing.md
  - type: Folder
    id: 64c98aad-e5de-4ae2-adb4-2ae8f6727441
    name: Characters
    children: []
  - type: Folder
    id: 5ff8a43c-d1e7-4568-a0aa-db4616b92258
    name: Places
    children: []
  - type: Folder
    id: 076eb445-5e89-4af6-840f-2b913053839d
    name: Front Matter
    children:
    - type: Document
      id: 1c96610d-b576-4276-b210-1d77b19ff945
      name: First Page Header
      path: manuscript/first-page-header.md
  - type: Folder
    id: 3822b3c0-0b0a-4bcf-96cd-71d89f8c27a8
    name: Notes
    children:
    - type: Document
      id: 3cf79249-63ce-455d-b916-99b4b61c9284
      name: Corn's POV
      path: manuscript/corn-s-pov.md
    - type: Document
      id: ff40ca11-3640-41fd-9bae-a09505bb4bb9
      name: Bits
      path: manuscript/bits.md
    - type: Document
      id: 876f13d8-c69a-40d3-ba7d-3b0cbc88dedc
      name: Old Corn
      path: manuscript/old-corn.md
  - type: Folder
    id: 679362f0-edaa-4704-bb43-399a7e866008
    name: Template Sheets
    children:
    - type: Document
      id: 15a97385-5397-4301-9f95-16ba92963684
      name: Character Sketch
      path: manuscript/character-sketch.md
    - type: Document
      id: 8461f893-e74a-49bc-9c8d-37aee57b5601
      name: Setting Sketch
      path: manuscript/setting-sketch.md
- type: Folder
  id: 0051c9b8-5d00-42e3-b537-c8c60f4ff667
  name: Research
  children:
  - type: Document
    id: 87e60926-ae62-4036-8808-47a4742690ed
    name: Sample Story MS
    path: research/sample-story-ms.pdf
- type: Folder
  id: bb35be3b-d579-4a98-9b54-5799436dd4c6
  name: Trash
  children: []
created: 2026-07-11T08:35:53.242818+00:00
modified: 2026-07-11T08:35:54.212873+00:00
metadata: {}
