id: 8d9f6c30-317e-4aea-9c34-1dbc5c8d6b44
name: Corn 2
created: 2025-10-04T10:55:11.7479390-04:00
modified: 2026-04-21T18:08:23.5385350Z
metadata:
  title: Corn 2
  author: ''
  project_type: short story
  genre: ''
  theme: ''
  summary: ''
hierarchy:
- id: ab89bbfe-c688-4aaf-8ad0-e61eef081eb6
  name: Short Story Format
  type: document
  path: manuscript/short-story-format.md
  children:
- id: manuscript
  name: Manuscript
  type: folder
  path:
  children:
  - id: b8440d1b-921f-4666-af05-7f537d260e80
    name: Opening
    type: document
    path: manuscript/opening.md
    children:
  - id: 7691f802-fabb-4285-a678-edef1d712a64
    name: Shelly & Marcus setup
    type: document
    path: manuscript/shelly-marcus-setup.md
    children:
  - id: 32e63e75-e7df-448d-bae6-e14d0d711919
    name: Shelly & Corn meet
    type: document
    path: manuscript/shelly-corn-meet.md
    children:
  - id: 1b70b7ad-8d68-4369-8100-14b5218955a5
    name: S&C Falling
    type: document
    path: manuscript/s-c-falling.md
    children:
  - id: 65b936d8-b951-4d9f-bdbb-45cfcb936ec4
    name: S&C Getting intimate
    type: document
    path: manuscript/s-c-getting-intimate.md
    children:
  - id: 454aed9f-74c2-4390-8a80-d60bdfa15a2e
    name: Daddy's letter arrives
    type: document
    path: manuscript/daddy-s-letter-arrives.md
    children:
  - id: 1733badd-c3a3-4213-95c9-94e3b4a0470a
    name: Shelly's house, Corn vs Kelly
    type: document
    path: manuscript/shelly-s-house-corn-vs-kelly.md
    children:
  - id: 85476ff5-bba9-456b-9101-4952b88df980
    name: Motel confrontation
    type: document
    path: manuscript/motel-confrontation.md
    children:
  - id: 7e596ed5-4634-4a8a-b01a-27bc3704fa07
    name: Closing
    type: document
    path: manuscript/closing.md
    children:
- id: research
  name: Research
  type: folder
  path:
  children:
  - id: notes-folder-001
    name: Notes
    type: folder
    path:
    children:
    - id: c38b54c6-1259-4f84-8e65-3b759a4839fa
      name: Corn's POV
      type: document
      path: manuscript/corn-s-pov.md
      children:
    - id: b28b3dfd-d346-4d88-a1ef-b9e043f137c7
      name: Old Corn
      type: document
      path: manuscript/old-corn.md
      children:
    - id: e4a0f2f2-c0ac-4ea1-840c-006256852d81
      name: Bits
      type: document
      path: manuscript/bits.md
      children:
  - id: characters-folder-001
    name: Characters
    type: folder
    path:
    children:
    - id: 684cefcf-260b-4a7d-a616-9f0fcc562b3c
      name: Character Sketch
      type: document
      path: manuscript/character-sketch.md
      children:
  - id: settings-folder-001
    name: Settings
    type: folder
    path:
    children:
    - id: 5fe0d74e-cccf-4dd7-a156-d5cad513b4e4
      name: Setting Sketch
      type: document
      path: manuscript/setting-sketch.md
      children:
  - id: 82ebf096-21d1-483c-a294-15e76329110a
    name: First Page Header
    type: document
    path: manuscript/first-page-header.md
    children:
- id: trash
  name: Trash
  type: folder
  path:
  children:
  - id: 0e14ca19-fb25-46a7-98a8-8977838101a0
    name: New Document
    type: document
    path: manuscript/new-document.md
    children:
  - id: 94f4a337-a354-4a4b-9c82-05749c00be51
    name: New Document
    type: document
    path: manuscript/new-document-2.md
    children:
  - id: 71c88465-2d79-4ea5-8629-d5dc7d07f07c
    name: New Document
    type: document
    path: manuscript/new-document-3.md
    children:
